<a href="https://colab.research.google.com/github/altierispeixoto/fundamentus/blob/main/notebooks/funds-explorer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://www.fundsexplorer.com.br/ranking

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.options.display.float_format = '{:.2f}'.format

In [2]:
import urllib.request

user_agent = 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.7) Gecko/2009021910 Firefox/3.0.7'

url = "https://www.fundsexplorer.com.br/ranking"
headers={'User-Agent':user_agent,} 

request=urllib.request.Request(url,None,headers) #The assembled request
response = urllib.request.urlopen(request)
data = response.read()

In [3]:
df = pd.read_html(data,encoding='utf-8', decimal=',', thousands='.')

In [4]:
df = df[0]

In [5]:
df[(df['Códigodo fundo'] == 'KNRI11' )].head()

,Códigodo fundo,Setor,Preço Atual,Liquidez Diária,Dividendo,DividendYield,DY (3M)Acumulado,DY (6M)Acumulado,DY (12M)Acumulado,DY (3M)Média,DY (6M)Média,DY (12M)Média,DY Ano,Variação Preço,Rentab.Período,Rentab.Acumulada,PatrimônioLíq.,VPA,P/VPA,DYPatrimonial,VariaçãoPatrimonial,Rentab. Patr.no Período,Rentab. Patr.Acumulada,VacânciaFísica,VacânciaFinanceira,QuantidadeAtivos
77,KNRI11,Híbrido,"R$ 140,90",245930.00,"R$ 0,77","0,52%","1,53%","2,97%","5,51%","0,51%","0,49%","0,46%","4,29%","3,40%","3,94%","-3,99%","R$ 3.800.803.257,11","R$ 157,34",0.90,"0,49%","-0,30%","0,19%","1,96%","3,35%","8,16%",20

In [6]:
columns = {"Códigodo fundo":"cod",
           "Setor":"setor",
           "Preço Atual":"preco_R$",
           "Liquidez Diária":"liq_diaria",
           "Dividendo":"dividendo_R$",
           "DividendYield":"div_yield_pct",
           "DY (3M)Acumulado":"div_yield_3M_pct",
           "DY (6M)Acumulado":"div_yield_6M_pct",
           "DY (12M)Acumulado":"div_yield_12M_pct",
           "DY (3M)Média":"div_yield_3M_pct_media",
           "DY (6M)Média":"div_yield_6M_pct_media",
           "DY (12M)Média":"div_yield_12M_pct_media",
           "DY Ano":"div_yield_ano_pct",
           "Variação Preço":"var_preco_pct",
           "Rentab.Período":"rent_periodo_pct",
           "Rentab.Acumulada":"rent_acum_pct",
           "PatrimônioLíq.":"patr_liq_R$",
           "VPA":"vpa_R$",
           "P/VPA":"p_vpa",
           "DYPatrimonial":"dy_patrimonial",
           "VariaçãoPatrimonial":"var_patr_pct",
           "Rentab. Patr.no Período":"rent_patri_no_periodo_pct",
           "Rentab. Patr.Acumulada":"rent_patri_acum_pct",
           "VacânciaFísica":"vac_fisica_pct",
           "VacânciaFinanceira":"vac_financeira_pct",
           "QuantidadeAtivos":"nr_ativos"
}
                      
df = df.rename(columns = columns)

In [8]:
df['preco_R$'] = df['preco_R$'].map(lambda x : float(str(x).replace('R$','').replace('.','').replace(',','.')))
df['dividendo_R$'] = df['dividendo_R$'].map(lambda x : float(str(x).replace('R$','').replace(',','.')))
df['patr_liq_R$'] = df['patr_liq_R$'].map(lambda x : float(str(x).replace('R$','').replace('.','').replace(',','.')))
df['vpa_R$'] = df['vpa_R$'].map(lambda x : float(str(x).replace('R$','').replace('.','').replace(',','.')))


df['div_yield_pct'] = df['div_yield_pct'].map(lambda x : float(str(x).replace('%','').replace(',','.')))
df['div_yield_3M_pct'] = df['div_yield_3M_pct'].map(lambda x : float(str(x).replace('%','').replace(',','.')))
df['div_yield_6M_pct'] = df['div_yield_6M_pct'].map(lambda x : float(str(x).replace('%','').replace(',','.')))
df['div_yield_12M_pct'] = df['div_yield_12M_pct'].map(lambda x : float(str(x).replace('%','').replace(',','.')))
df['div_yield_3M_pct_media'] = df['div_yield_3M_pct_media'].map(lambda x : float(str(x).replace('%','').replace(',','.')))

df['div_yield_6M_pct_media'] = df['div_yield_6M_pct_media'].map(lambda x : float(str(x).replace('%','').replace(',','.')))

df['div_yield_12M_pct_media'] = df['div_yield_12M_pct_media'].map(lambda x : float(str(x).replace('%','').replace(',','.')))
df['div_yield_ano_pct'] = df['div_yield_ano_pct'].map(lambda x : float(str(x).replace('%','').replace(',','.')))
df['var_preco_pct'] = df['var_preco_pct'].map(lambda x : float(str(x).replace('%','').replace(',','.')))
#df['rent_acum_pct'] = df['rent_acum_pct'].map(lambda x : float(str(x).replace('%','').replace(',','.')))

df['dy_patrimonial'] = df['dy_patrimonial'].map(lambda x : float(str(x).replace('%','').replace(',','.')))
df['var_patr_pct'] = df['var_patr_pct'].map(lambda x : float(str(x).replace('%','').replace(',','.')))
df['rent_patri_no_periodo_pct'] = df['rent_patri_no_periodo_pct'].map(lambda x : float(str(x).replace('%','').replace(',','.')))
df['rent_patri_acum_pct'] = df['rent_patri_acum_pct'].map(lambda x : float(str(x).replace('%','').replace('.','').replace(',','.')))

df['vac_fisica_pct'] = df['vac_fisica_pct'].map(lambda x : float(str(x).replace('%','').replace(',','.')))
df['vac_financeira_pct'] = df['vac_financeira_pct'].map(lambda x : float(str(x).replace('%','').replace(',','.')))

df['rent_periodo_pct'] = df['rent_periodo_pct'].map(lambda x : float(str(x).replace('%','').replace(',','.')))

In [10]:
#df.to_csv("data/fundsexplorer_raw.csv",index=False)

In [20]:
#df = pd.read_csv("data/fundsexplorer_raw.csv")

In [12]:
df[(df['cod'].isin(['ABCP11','BCRI11','BBPO11','CPTS11B','EDFO11B','FVPQ11','FIIB11','HGBS11','HGCR11','HGLG11','HGPO11','HGRE11','KNCR11','KNRI11','KNHY11','MALL11','MXRF11','OUJP11','PQDP11','SDIL11','TGAR11','VRTA11','VISC11','XPLG11']))][['cod','setor']].sort_values(['setor'])

         cod                setor
35    FIIB11              Híbrido
152   MXRF11              Híbrido
77    KNRI11              Híbrido
158   HGPO11   Lajes Corporativas
160   HGRE11   Lajes Corporativas
70    BBPO11   Lajes Corporativas
66   EDFO11B   Lajes Corporativas
99    XPLG11            Logística
157   HGLG11            Logística
92    SDIL11            Logística
93    SDIL11            Logística
144   TGAR11               Outros
143   ABCP11            Shoppings
138   FVPQ11            Shoppings
127   MALL11            Shoppings
75    PQDP11            Shoppings
97    VISC11            Shoppings
80    HGBS11            Shoppings
135   KNCR11  Títulos e Val. Mob.
118   VRTA11  Títulos e Val. Mob.
110   HGCR11  Títulos e Val. Mob.
46    BCRI11  Títulos e Val. Mob.
74    KNHY11  Títulos e Val. Mob.
120   OUJP11  Títulos e Val. Mob.

In [13]:
df = df[~(df['setor'].isin(['Hospital','Hotel','Residencial']))].sort_values(['setor','cod'])[['cod','setor','preco_R$','liq_diaria','dividendo_R$','vac_fisica_pct','vac_financeira_pct','vpa_R$','p_vpa','div_yield_12M_pct','div_yield_12M_pct_media','div_yield_pct','nr_ativos']]

In [24]:
df.shape[0]

234

In [14]:
df['setor'].unique()

array(['Híbrido', 'Lajes Corporativas', 'Logística', 'Outros',
       'Shoppings', 'Títulos e Val. Mob.'], dtype=object)

In [22]:
df[(df['setor']=='Títulos e Val. Mob.')].sort_values(['div_yield_pct'],ascending=False)[['cod','preco_R$','liq_diaria','dividendo_R$','vpa_R$','p_vpa','div_yield_12M_pct_media','div_yield_12M_pct','div_yield_pct']]

,cod,preco_R$,liq_diaria,dividendo_R$,vpa_R$,p_vpa,div_yield_12M_pct_media,div_yield_12M_pct,div_yield_pct
126,HABT11,11247.00,370120.00,1.50,9717.00,1.16,1.28,15.40,1.32
229,OURE11,8705.00,12720.00,1.10,9629.00,0.90,0.90,10.79,1.29
202,FLCR11,1020.00,26810.00,1.33,10074.00,1.01,0.00,0.00,1.29
184,DEVA11,1017.00,834060.00,1.33,982.00,1.04,0.00,0.00,1.29
161,VGHF11,986.00,674660.00,0.13,943.00,1.05,0.00,0.00,1.28
130,VCJR11,9585.00,174310.00,1.22,9648.00,0.99,0.86,10.38,1.28
128,KNSC11,987.00,349030.00,1.24,9134.00,1.08,0.00,0.00,1.25
203,CVBI11,1017.00,313030.00,1.23,9993.00,1.02,1.10,13.23,1.20
240,MCHY11,1345.00,200.00,1.30,10011.00,1.34,0.00,0.00,1.18
88,KNIP11,1030.00,1093660.00,1.20,9828.00,1.05,1.00,11.99,1.15
106,ARRI11,968.00,23320.00,1.11,9507.00,1.02,1.06,12.68,1.14
60,HSAF11,9062.00,47790.00,1.00,9522.00,0.95,0.87,10.41,1.11
226,AFHI11,937.00,45420.00,1.05,9763.00,0.96,0.00,0.00,1.10
90,BARI11,10356.00,175440.00,1.15,10214.00,1.01,1.17,14.07,1.09
54,RBHY11,985.00,5110.00,1.10,9951.00,0.99,0.00,0.00,1.08
201,RECR11,9959.00,896590.00,1.09,9519.00,1.05,1.12,13.48,1.07
237,AFOF11,8131.00,7930.00,0.84,10058.00,0.81,0.00,0.00,1.06
83,JPPA11,9375.00,12320.00,1.00,10371.00,0.90,0.90,10.78,1.05
58,RRCI11,7943.00,14650.00,0.84,9745.00,0.82,0.00,0.00,1.04
120,OUJP11,8939.00,48460.00,0.90,10323.00,0.87,0.76,9.11,1.02
223,GCRI11,989.00,4770.00,1.02,10126.00,0.98,0.00,0.00,1.02
38,IFID11,8398.00,2040.00,0.83,8891.00,0.94,0.00,0.00,1.01
118,VRTA11,10799.00,193140.00,1.10,9796.00,1.10,0.83,10.00,1.01
46,BCRI11,1087.00,136550.00,1.11,10582.00,1.03,1.03,12.36,1.01
212,CPTS11,9814.00,876220.00,1.00,9414.00,1.04,1.01,12.06,1.00
74,KNHY11,1050.00,274770.00,1.07,979.00,1.07,1.03,12.41,1.00
215,MCCI11,10035.00,498810.00,1.00,10024.00,1.00,0.77,9.27,0.99
42,PORD11,9485.00,53130.00,0.91,990.00,0.96,0.88,10.57,0.95
189,EQIN11,937.00,100770.00,0.88,9417.00,0.99,0.93,11.13,0.94
227,OUFF11,6825.00,38910.00,0.65,8117.00,0.84,0.80,9.61,0.94
210,IRDM11,1120.00,897000.00,1.05,9697.00,1.16,0.93,11.19,0.92
207,RBRR11,977.00,393580.00,0.90,9978.00,0.98,0.72,8.62,0.91
222,MGCR11,8593.00,9120.00,0.80,9491.00,0.91,0.00,0.00,0.91
195,FEXC11,838.00,58260.00,0.75,9347.00,0.90,0.77,9.28,0.89
246,RBHG11,800.00,44380.00,0.75,9635.00,0.83,0.75,9.03,0.88
206,RBRY11,10199.00,50680.00,0.90,10349.00,0.99,0.76,9.11,0.87
224,GCFF11,7638.00,6440.00,0.67,9017.00,0.85,0.88,10.53,0.86
221,MORE11,818.00,135150.00,0.70,932.00,0.88,0.73,8.71,0.86
205,RVBI11,8426.00,36540.00,0.75,8857.00,0.95,0.77,9.20,0.85
176,BLMR11,748.00,1556720.00,0.07,883.00,0.85,0.00,0.00,0.85
150,VIFI11,7501.00,49430.00,0.63,9177.00,0.82,0.70,8.36,0.84
232,RZAK11,8692.00,241700.00,0.75,9604.00,0.90,0.00,0.00,0.83
219,NAVT11,7201.00,60910.00,0.60,916.00,0.79,0.00,0.00,0.83
131,HGIC11,10588.00,650.00,0.90,10509.00,1.01,0.00,0.00,0.83
154,VIUR11,808.00,15560.00,0.67,9587.00,0.84,0.00,0.00,0.80
194,BTCR11,912.00,57840.00,0.75,9764.00,0.93,0.71,8.48,0.80
129,BPFF11,6701.00,87900.00,0.55,7882.00,0.85,0.71,8.57,0.80
59,RFOF11,7849.00,13590.00,0.63,8633.00,0.91,0.75,9.04,0.79
110,HGCR11,10559.00,376530.00,0.85,10275.00,1.03,0.72,8.64,0.79
47,BBFO11,7258.00,11370.00,0.60,8784.00,0.83,0.00,0.00,0.79
209,IBFF11,6194.00,44510.00,0.50,7669.00,0.81,0.62,7.49,0.78
159,RBFF11,593.00,54250.00,0.47,6763.00,0.88,0.72,8.62,0.78
208,RBRF11,7708.00,312190.00,0.60,8611.00,0.90,0.72,8.69,0.76
225,SNFF11,9268.00,125060.00,0.70,9225.00,1.00,0.00,0.00,0.74
190,MGFF11,684.00,261970.00,0.50,7849.00,0.87,0.69,8.34,0.74
56,BCIA11,8521.00,60170.00,0.64,10438.00,0.82,0.63,7.52,0.74
86,RDPD11,6556.00,270.00,0.50,7063.00,0.93,0.60,7.25,0.73
141,KFOF11,825.00,45220.00,0.58,9531.00,0.87,0.60,7.19,0.72
57,KISU11,795.00,2847270.00,0.06,924.00,0.86,0.00,0.00,0.72
121,HREC11,9788.00,270.00,0.70,9442.00,1.04,0.00,0.00,0.71
78,HFOF11,850.00,265000.00,0.60,8823.00,0.96,0.60,7.25,0.70
193,BCFF11,7033.00,561820.00,0.50,801.00,0.88,0.61,7.30,0.69
217,VGIR11,9558.00,82510.00,0.65,9698.00,0.99,0.58,6.92,0.67
155,HGFF11,736.00,53990.00,0.50,8995.00,0.82,0.63,7.60,0.66
40,IFIE11,7603.00,770.00,0.50,8216.00,0.93,0.00,0.00,0.65
134,VOTS11,800.00,1640.00,0.55,9853.00,0.81,0.56,6.77,0.65
50,PLRI11,440.00,14720.00,0.28,4893.00,0.90,0.56,6.67,0.60
36,BICR11,9779.00,100.00,0.55,993.00,0.98,0.32,3.88,0.59
169,CRFF11,6881.00,1080.00,0.40,8749.00,0.79,0.56,6.73,0.58
135,KNCR11,9699.00,489180.00,0.55,9948.00,0.97,0.40,4.77,0.57
105,SADI11,8336.00,7000.00,0.46,10051.00,0.83,0.32,3.86,0.56
55,QIRI11,8602.00,910.00,0.49,8966.00,0.96,0.68,8.16,0.52
132,RNDP11,66153.00,50.00,2.00,76322.00,0.87,0.52,6.22,0.28
111,BBIM11,nan,nan,0.70,5013.00,nan,0.00,0.00,0.00
1,BZLI11,147.00,440410.00,0.00,1103.00,1.33,0.00,0.00,0.00
6,ORPD11,1320.00,10.00,1.38,15181.00,0.87,nan,nan,nan

In [16]:
df[(df['setor']=='Logística')  & (df['nr_ativos'] > 5) & (df['preco_R$'] < 1000)]

,cod,setor,preco_R$,liq_diaria,dividendo_R$,vac_fisica_pct,vac_financeira_pct,vpa_R$,p_vpa,div_yield_12M_pct,div_yield_12M_pct_media,div_yield_pct,nr_ativos
96,BRCO11,Logística,987.00,626330.00,0.57,0.00,2.70,10853.00,0.91,6.02,0.50,0.58,10
117,LVBI11,Logística,995.00,366700.00,0.65,2.30,0.00,11471.00,0.87,5.69,0.47,0.64,10
197,RBRL11,Logística,915.00,117060.00,0.75,0.00,0.00,10667.00,0.86,7.59,0.63,0.78,6

In [17]:
df[(df['setor']=='Shoppings') & (df['nr_ativos'] > 5) & (df['preco_R$'] < 1000)]

,cod,setor,preco_R$,liq_diaria,dividendo_R$,vac_fisica_pct,vac_financeira_pct,vpa_R$,p_vpa,div_yield_12M_pct,div_yield_12M_pct_media,div_yield_pct,nr_ativos
10,GSFI11,Shoppings,43.00,190530.00,0.00,9.50,nan,1324.00,0.32,0.03,0.00,0.03,10

In [18]:
df[(df['setor']=='Híbrido') & (df['nr_ativos'] > 5) & (df['preco_R$'] < 1000) ]

,cod,setor,preco_R$,liq_diaria,dividendo_R$,vac_fisica_pct,vac_financeira_pct,vpa_R$,p_vpa,div_yield_12M_pct,div_yield_12M_pct_media,div_yield_pct,nr_ativos
156,GALG11,Híbrido,995.00,473340.00,0.84,0.00,0.00,10349.00,0.96,0.00,0.00,0.82,6
114,HSRE11,Híbrido,990.00,110.00,0.56,0.00,nan,9725.00,1.02,0.00,0.00,0.57,29
147,RZTR11,Híbrido,990.00,537440.00,0.95,nan,nan,9844.00,1.01,0.00,0.00,0.95,10

In [19]:
df[(df['setor']=='Lajes Corporativas') & (df['nr_ativos'] > 5) & (df['preco_R$'] < 1000)]

,cod,setor,preco_R$,liq_diaria,dividendo_R$,vac_fisica_pct,vac_financeira_pct,vpa_R$,p_vpa,div_yield_12M_pct,div_yield_12M_pct_media,div_yield_pct,nr_ativos
70,BBPO11,Lajes Corporativas,917.00,207350.00,0.82,0.00,0.00,9588.00,0.96,10.57,0.88,0.84,64
62,PATC11,Lajes Corporativas,630.00,31510.00,0.30,27.20,30.10,8554.00,0.74,5.01,0.42,0.47,6